//
// Created by Nutellis on 13-Feb-26.
//

#ifndef ALKYONERENDERENGINE_COREDEFINITIONS_H
#define ALKYONERENDERENGINE_COREDEFINITIONS_H

#define RHI_VULKAN_BACKEND


#endif //ALKYONERENDERENGINE_COREDEFINITIONS_H