//
// Created by Nutellis on 30-Jan-26.
//

#ifndef ALKYONERENDERENGINE_PIPELINEDESCR_H
#define ALKYONERENDERENGINE_PIPELINEDESCR_H

#include <core/PODTypes.h>

typedef enum LogicOp {
    OP_CLEAR = 0, // VK_LOGIC_OP_CLEAR | D3D12_LOGIC_OP_CLEAR
    OP_AND, // VK_LOGIC_OP_AND | D3D12_LOGIC_OP_AND
    OP_AND_REVERSE, // VK_LOGIC_OP_AND_REVERSE | D3D12_LOGIC_OP_AND_REVERSE
    OP_COPY, // VK_LOGIC_OP_COPY | D3D12_LOGIC_OP_COPY,
    OP_AND_INVERTED, // VK_LOGIC_OP_AND_INVERTED | D3D12_LOGIC_OP_AND_INVERTED,
    OP_NO_OP, // VK_LOGIC_OP_NO_OP | D3D12_LOGIC_OP_NOOP
    OP_XOR, // VK_LOGIC_OP_XOR | D3D12_LOGIC_OP_XOR
    OP_OR, // VK_LOGIC_OP_OR | D3D12_LOGIC_OP_OR
    OP_NOR, // VK_LOGIC_OP_NOR | D3D12_LOGIC_OP_NOR
    OP_EQUIVALENT, // VK_LOGIC_OP_EQUIVALENT | D3D12_LOGIC_OP_EQUIV
    OP_INVERT, // VK_LOGIC_OP_INVERT | D3D12_LOGIC_OP_INVERT
    OP_OR_REVERSE, // VK_LOGIC_OP_OR_REVERSE | D3D12_LOGIC_OP_OR_REVERSE
    OP_COPY_INVERTED, // VK_LOGIC_OP_COPY_INVERTED | D3D12_LOGIC_OP_COPY_INVERTED
    OP_OR_INVERTED, // VK_LOGIC_OP_OR_INVERTED | D3D12_LOGIC_OP_OR_INVERTED
    OP_NAND, // VK_LOGIC_OP_NAND | D3D12_LOGIC_OP_NAND
    OP_SET, // VK_LOGIC_OP_SET | D3D12_LOGIC_OP_SET
};

enum PrimitiveTopology
{
    PRIMITIVE_TOPOLOGY_UNDEFINED = 0,
    PRIMITIVE_TOPOLOGY_POINT, // VK_PRIMITIVE_TOPOLOGY_POINT_LIST  | D3D_PRIMITIVE_TOPOLOGY_POINTLIST
    PRIMITIVE_TOPOLOGY_LINE, // VK_PRIMITIVE_TOPOLOGY_LINE_LIST | D3D_PRIMITIVE_TOPOLOGY_LINELIST
    PRIMITIVE_TOPOLOGY_LINE_STRIP, // VK_PRIMITIVE_TOPOLOGY_LINE_STRIP | D3D_PRIMITIVE_TOPOLOGY_LINESTRIP
    PRIMITIVE_TOPOLOGY_TRIANGLE, // VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST | D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST
    PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP, // VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP | D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP
    PRIMITIVE_TOPOLOGY_TRIANGLE_FAN // VK_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN | D3D_PRIMITIVE_TOPOLOGY_TRIANGLEFAN
};

enum CompareOp
{
    OP_NEVER, // VK_COMPARE_OP_NEVER | D3D12_COMPARISON_FUNC_NEVER
    OP_LESS, // VK_COMPARE_OP_LESS | D3D12_COMPARISON_FUNC_LESS
    OP_EQUAL, // VK_COMPARE_OP_EQUAL | D3D12_COMPARISON_FUNC_EQUAL
    OP_LESS_EQUAL, // VK_COMPARE_OP_LESS_OR_EQUAL | D3D12_COMPARISON_FUNC_LESS_EQUAL
    OP_GREATER, // VK_COMPARE_OP_GREATER | D3D12_COMPARISON_FUNC_GREATER
    OP_NOT_EQUAL, // VK_COMPARE_OP_NOT_EQUAL | D3D12_COMPARISON_FUNC_NOT_EQUAL
    OP_GREATER_EQUAL, // VK_COMPARE_OP_GREATER_OR_EQUAL | D3D12_COMPARISON_FUNC_GREATER_EQUAL
    OP_ALWAYS, // VK_COMPARE_OP_ALWAYS | D3D12_COMPARISON_FUNC_ALWAYS
    OP_NONE = 0, // D3D12_COMPARISON_FUNC_NONE
};

enum Format
{
    FORMAT_R32G32B32_SFLOAT, // VK_FORMAT_R32G32B32_SFLOAT
    FORMAT_R32G32_SFLOAT // VK_FORMAT_R32G32_SFLOAT
};



struct GraphicsPipelineDesc
{
    //shaders of type Slang::ComPtr<slang::IModule>. For starters, we support separate files for each shader to avoid complexity
    // vertex
    // fragment/pixel
    //tessellation related (hull domain)
    //geometry


    uint32 viewportCount;
    uint32 scissorCount;

    bool logicOpEnable;
    LogicOp logicOp;

    uint32 renderTargetCount; // attachmentCount | renderTarget

    PrimitiveTopology primitiveTopology;

    bool depthTestEnable;
    bool depthWriteEnable;
    CompareOp depthCompareOp;
};



#endif //ALKYONERENDERENGINE_PIPELINEDESCR_H