//
// Created by Nutellis on 30-Jan-26.
//

#ifndef ALKYONERENDERENGINE_VULKANDEFINITIONS_H
#define ALKYONERENDERENGINE_VULKANDEFINITIONS_H

#include <vulkan/vulkan.h>

static const VkCompareOp VulkanCompareOps[] = {
    VK_COMPARE_OP_NEVER,
    VK_COMPARE_OP_LESS,
    VK_COMPARE_OP_EQUAL,
    VK_COMPARE_OP_LESS_OR_EQUAL,
    VK_COMPARE_OP_GREATER,
    VK_COMPARE_OP_NOT_EQUAL,
    VK_COMPARE_OP_GREATER_OR_EQUAL,
    VK_COMPARE_OP_ALWAYS
};


#endif //ALKYONERENDERENGINE_VULKANDEFINITIONS_H