//
// Created by Nutellis on 20-Feb-26.
//

#ifndef ALKYONERENDERENGINE_RHIDEFINITIONS_H
#define ALKYONERENDERENGINE_RHIDEFINITIONS_H
enum TransitionFlags
{
    STATE_UNDEFINED = 0,
    STATE_GENERAL,
    STATE_COLOUR_ATTACHMENT,
    STATE_DEPTH_STENCIL_ATTACHMENT,
    STATE_DEPTH_STENCIL_READ_ONLY,
    STATE_SHADER_READ_ONLY,
    STATE_TRANSFER_SRC,
    STATE_PRESENT_SRC
};

enum class StageFlagBits : uint32
{
    STAGE_NONE = 0,
    STAGE_TOP_OF_PIPE = BIT(0),
    STAGE_DRAW_INDIRECT = BIT(1),
    STAGE_VERTEX_INPUT = BIT(2),
    STAGE_VERTEX_SHADER = BIT(3),
    STAGE_FRAGMENT_SHADER = BIT(4),
    STAGE_COLOUR_ATTACHMENT_OUTPUT = BIT(5),
    STAGE_COMPUTE_SHADER = BIT(6),
    STAGE_ALL_COMMANDS = BIT(7)
};

enum class AccessMaskFlagBits : uint32
{
    ACCESS_NONE = 0,
    ACCESS_INDIRECT_COMMAND_READ = BIT(0),
    ACCESS_INDEX_READ = BIT(1),
    ACCESS_VERTEX_ATTRIBUTE_READ = BIT(2),
    ACCESS_UNIFORM_READ = BIT(3),
    ACCESS_INPUT_ATTACHMENT_READ = BIT(4),
    ACCESS_SHADER_READ = BIT(5),
    ACCESS_SHADER_WRITE = BIT(6),
    ACCESS_COLOUR_ATTACHMENT_READ = BIT(7),
    ACCESS_COLOUR_ATTACHMENT_WRITE = BIT(8),
    ACCESS_DEPTH_STENCIL_ATTACHMENT_READ = BIT(9),
    ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE = BIT(10),
    ACCESS_TRANSFER_READ = BIT(11),
    ACCESS_TRANSFER_WRITE = BIT(12),
    // ACCESS_HOST_READ = ...;
    // ACCESS_HOST_WRITE = ...;
    ACCESS_MEMORY_READ = BIT(13),
    ACCESS_MEMORY_WRITE = BIT(14)
};

enum class ImageAspectFlagBits : uint32
{
    ASPECT_NONE = 0,
    ASPECT_COLOUR_BIT = BIT(0),
    ASPECT_DEPTH_BIT = BIT(1),
    ASPECT_STENCIL_BIT = BIT(2),
    ASPECT_METADATA_BIT = BIT(3)

};



#endif //ALKYONERENDERENGINE_RHIDEFINITIONS_H