//
// Created by Nutellis on 11-Feb-26.
//

#ifndef ALKYONERENDERENGINE_COMMANDPOOLDESC_H
#define ALKYONERENDERENGINE_COMMANDPOOLDESC_H
#include <cstdint>

enum CommandPoolCreateFlagBits {
    COMMAND_POOL_CREATE_TRANSIENT_BIT = 0, // VK_COMMAND_POOL_CREATE_TRANSIENT_BIT
    COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT, // VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT
    COMMAND_POOL_CREATE_PROTECTED_BIT, // VK_COMMAND_POOL_CREATE_PROTECTED_BIT
};





struct CommandPoolDesc
{
    CommandPoolCreateFlagBits FlagBits;
    uint32_t queueFamilyIndex;
};

#endif //ALKYONERENDERENGINE_COMMANDPOOLDESC_H